# Site settings
title: The Working Party
email: marcnewport@gmail.com
description: A digital agency specialising in shopify plus based in Sydney and Melbourne
url: "http://pest-exterminator-disease-12105.netlify.com" # the base hostname & protocol for your site - used for feed.xml

collections:
    works:
        output: true
    news:
        output: true

# Build settings
markdown: kramdown
exclude: [bower_components, node_modules, bower.json, gulpfile.js, package.json, README.md]
